FROM alpine as builder
RUN apk upgrade -q --no-cache
RUN apk add -q --no-cache \
      bash \
      gettext \
      git \
      maven \
      openjdk8 \
      openjdk8-jre-base \
      openssl \
      unzip \
      zip 


